/** Environment variable keys used by Foundation hosts. */
export const EnvKeys = {
  API_PORT: 'ATI_API_PORT',
  WORKER_PORT: 'ATI_WORKER_PORT',
  NODE_ENV: 'ATI_NODE_ENV',
  LOG_LEVEL: 'ATI_LOG_LEVEL',
  PLATFORM_VERSION: 'ATI_PLATFORM_VERSION',
  FEATURE_FLAGS: 'ATI_FEATURE_FLAGS',
  AUTH_ENABLED: 'ATI_AUTH_ENABLED',
  AUTH_ISSUER: 'ATI_AUTH_ISSUER',
  AUTH_AUDIENCE: 'ATI_AUTH_AUDIENCE',
  AUTH_JWKS_URI: 'ATI_AUTH_JWKS_URI',
  AUTH_ALGORITHMS: 'ATI_AUTH_ALGORITHMS',
  AUTH_PUBLIC_ROUTES: 'ATI_AUTH_PUBLIC_ROUTES',
  AUTH_CLAIM_ROLE_MAP: 'ATI_AUTH_CLAIM_ROLE_MAP',
  AUTH_CLOCK_SKEW_SECONDS: 'ATI_AUTH_CLOCK_SKEW_SECONDS',
  OBS_ENABLED: 'ATI_OBS_ENABLED',
  OTEL_ENABLED: 'ATI_OTEL_ENABLED',
  OTEL_EXPORTER_OTLP_ENDPOINT: 'ATI_OTEL_EXPORTER_OTLP_ENDPOINT',
  OTEL_SERVICE_NAME: 'ATI_OTEL_SERVICE_NAME',
  OTEL_TRACES_SAMPLER_ARG: 'ATI_OTEL_TRACES_SAMPLER_ARG',
  CONTEXT_ENABLED: 'ATI_CONTEXT_ENABLED',
  CONTEXT_ENFORCE_ON_PROTECTED: 'ATI_CONTEXT_ENFORCE_ON_PROTECTED',
  CONTEXT_DEFAULT_TENANT_ID: 'ATI_CONTEXT_DEFAULT_TENANT_ID',
  CONTEXT_DEFAULT_WORKSPACE_ID: 'ATI_CONTEXT_DEFAULT_WORKSPACE_ID',
  CONTEXT_SUBJECT_TENANT_MAP: 'ATI_CONTEXT_SUBJECT_TENANT_MAP',
  REQUIREMENT_ENGINE_ENABLED: 'ATI_REQUIREMENT_ENGINE_ENABLED',
  REQUIREMENT_ENGINE_REGISTER_STUB: 'ATI_REQUIREMENT_ENGINE_REGISTER_STUB',
  INTAKE_ENABLED: 'ATI_INTAKE_ENABLED',
  CLASSIFICATION_ENABLED: 'ATI_CLASSIFICATION_ENABLED',
  FEATURE_VERSION_ENABLED: 'ATI_FEATURE_VERSION_ENABLED',
} as const;

/** Well-known HTTP header names. */
export const HttpHeaders = {
  CORRELATION_ID: 'x-correlation-id',
  /**
   * Non-authoritative client hints only (WP-2.4 D2).
   * Hosts must never treat these as the source of execution context.
   */
  TENANT_ID: 'x-ati-tenant-id',
  WORKSPACE_ID: 'x-ati-workspace-id',
} as const;

export const DefaultPorts = {
  api: 3000,
  worker: 3001,
} as const;

export const DEFAULT_PLATFORM_VERSION = '0.0.0';
